### ISSUE TITLE
Plan for atmosphere upgrade into rails 4.2.1 + cleanup

### ISSUE THREAD

**Issue by mkasztelnik** [dice-cyfronet/atmosphere#143]
#139 and #141 are an intermediate steps for upgrading into rails 4.2.1. What is more I have additional future plans for atmosphere:

  * [x] #189 Update to rails 4.2.1
  * [ ] Migrate into [Active Jobs](http://edgeguides.rubyonrails.org/active_job_basics.html) and remove sidekiq dependency from atmosphere (projects which uses atmosphere can decide what kind of queue system to use)
  * [x] #146: Deliver unified template for all services. Simply is should looks as follow:

```ruby
class MyService
  def initialize(set, of, parameters)
    ...
  end

  def execute
    # do actual job
  end
end
```

  * [ ] Move time consuming tasks into delay jobs. Currently the more important thing to move is optimization and spawning virtual machine operations, which is done in synchronous way right now
  * [ ] Remove `actions` directory and move everything which is there into `services` directory
  * [ ] Create more accurate folder structure in `services` directory (`cloud`, `monitoring`, `proxy` is a good starting point)
  * [x] #151 Deliver instruction how migrations from engine can be used directly in projects which uses atmosphere. As a conclusion no `rake atmosphere:install:migrations` will be needed anymore
  * [ ] Make `Action` and `ActionLog` first class citizen and use it for spawning new appliance, saving appliance types, etc. 
  * [ ] Create error reporting logger class, which can have connectors to e.g. Sentry and remove sentry dependency from the atmosphere
  * [ ] The most important from the ISMOP perspective - focus on optimization process and make it more pluggable

@dice-cyfronet/atmo-dev-team please take a look at this points and submit any further changes which you see in the next atmosphere versions.

**Comment by mkasztelnik** [comment]
Another issues Atmosphere currently has is the usage of callbacks to invoke business logic. It can be seen in following places:
  * `after_create` in `Appliance` is used to trigger optimization process (what is worse this is synchronous process)
  * `after_destroy` in `Appliance` is used to trigger optimization process (and similar as above it is synchronous process)
  * `before_destroy` is used to bill appliance for the last time
  * `around_save` and `around_destroy` is used in `HttpMapping` to update or remove http/https redirection using redirus
  * `after_create` and `after_update` in `PortMappingTemplate` is used to create, update `PortMapping` using `IpWrangler`
  
All presented callbacks make Atmosphere quite fragile. If you are creating mentioned above objects in DB than you are not quite sure what will happen next :(

Instead of using callbacks I propose to use `Services`, which will create, update, remove DB object and if necessary invoke additional business logic.
